flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- HDBC-session-0.1.0.0
- HDBC-sqlite3-2.3.3.1
- names-th-0.1.0.1
- persistable-record-0.1.0.1
- relational-query-0.6.0.0
- relational-query-HDBC-0.1.0.1
- relational-schemas-0.1.0.2
- sql-words-0.1.3.1
resolver: lts-3.10
