Default: &defaults
  user: Yosog
  password: Yosog
  host: localhost
  port: 5432
  database: Yosog
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Yosog_test
  <<: *defaults

Staging:
  database: Yosog_staging
  poolsize: 100
  <<: *defaults

Production:
  user: nchckjxshuvary
  password: hJajjyloNHangjtRIubpyAWcl3
  host: ec2-54-204-32-91.compute-1.amazonaws.com
  port: 5432
  database: d8uon41vj1ik0l
  poolsize: 100
  <<: *defaults
